### ISSUE TITLE
More Docs

### ISSUE THREAD

**Issue by sinabehmanesh** [mahdi-malv/popclip-translate-shell#1]
Hey,
 
Notes:

- please add setup instructions
- add supported shells and systems
- add contribution Readme

**Comment by sinabehmanesh** [comment]
@mahdi-malv

**Comment by mahdi-malv** [comment]
There you go 4a32e403c7ef504ac00dbea5e841764c40552ce6

**Comment by sinabehmanesh** [comment]
I saw it and did not like it brother.
